export const formFields = [
  {
    id: "title",
    name: "title",
    label: "Product Title",
    type: "text",
    placeholder: "Enter product title",
    errorMessage: "Title is required and should be between 3-50 characters.",
    pattern: "^[a-zA-Z0-9 ]{3,50}$", // Letters, numbers, spaces, 3-50 characters
    required: true,
  },
  {
    id: "price",
    name: "price",
    label: "Product Price",
    type: "number",
    placeholder: "Enter product price",
    errorMessage: "Price must be a valid number greater than 0.",
    min: 0, // Minimum price
    required: true,
  },
  {
    id: "description",
    name: "description",
    label: "Product Description",
    type: "rte",
    placeholder: "Enter product description",
    rows: 5,
    errorMessage: "Description should be at least 10 characters long.",
    minLength: 10,
    required: true,
  },
  {
    id: "features",
    name: "features",
    label: "Product Features",
    type: "textarea",
    placeholder: "Enter product features (comma separated)",
    rows: 4,
    errorMessage: "Features should be a comma-separated list with at least one item.",
    pattern: "^(\\w+)(,\\s?\\w+)*$", // Comma-separated list
    required: true,
  },
  {
    id: "category",
    name: "category",
    label: "Product Category",
    type: "select",
    options: [
      { value: "", label: "Select Category" },
      { value: "smartphones", label: "Smartphones" },
      { value: "tablets", label: "Tablets" },
      { value: "laptops", label: "Laptops" },
      { value: "accessories", label: "Accessories" },
    ],
    errorMessage: "Please select a valid category.",
    required: true,
  },
  {
    id: "stock",
    name: "stock",
    label: "Product Stock",
    type: "number",
    placeholder: "Enter product stock",
    errorMessage: "Stock must be a valid number (0 or greater).",
    min: 0, // Minimum stock
    required: true,
  },
  {
    id: "mainImage",
    name: "mainImage",
    label: "Upload Main Product Image",
    type: "file",
    accept: "image/*",
    errorMessage: "Please upload a valid image file for the main product image.",
    required: true,
  },
  {
    id: "images",
    name: "images",
    label: "Upload Product Images (up to 5)",
    type: "file",
    accept: "image/*",
    multiple: true,
    errorMessage: "Please upload up to 5 valid image files.",
    maxFiles: 5, 
    required: false,
  },
];
